version: "3.1"
services:
  # Postgres DB
  db:
    image: mdillon/postgis
    env_file: .env
    container_name: ${PROJ_NAME}_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - web-db:/var/lib/postgresql/data
  
  # Django Backend   
  backend:
    build: .
    container_name: ${PROJ_NAME}_backend
    command: bash -c "sleep 5 && sh /usr/src/app/init_local.sh"
    env_file: .env
    environment:
      - ENVIRONMENT=local
      - DJANGO_DEBUG=True
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
volumes:
  web-db:
 
